from math import degrees, acos
a = int(input())
b = int(input())
c = int(input())
cos1 = (b **2 + c **2 - a ** 2) / (2 * b * c)
cos2 = (a ** 2 + c ** 2 - b ** 2) / (2 * a * c)
cos3 = (a ** 2 + b **2 - c ** 2)/(2 * a * b)
print(degrees(acos(cos1)))
print(degrees(acos(cos2)))
print(degrees(acos(cos3)))